const book = [
  {
    id: 1,
    chapter: "Array",
    subject: "Data structure",
  title:"Question",
    info: ` An operating system (OS) is the program that, after being initially loaded into the computer by a boot program, manages all of the other application programs in a computer.`,
  },
  {
    id: 2,
    chapter: "Memory system",
    subject: "Operating system",
  title:"Question",
    info: `An operating system (OS) is the program that, after being initially loaded into the computer by a boot program, manages all of the other application programs in a computer. `,
  },
  {
    id: 3,
    chapter: "Recursion",
    subject: "OOP",
  title:"Question",
  info: `An operating system (OS) is the program that, after being initially loaded into the computer by a boot program, manages all of the other application programs in a computer. `,
  },
  {
    id: 4,
    chapter: "country delight",
    subject: "Maths",
  title:"Question",
    info: `An operating system (OS) is the program that, after being initially loaded into the computer by a boot program, manages all of the other application programs in a computer.` ,
  },
  {
    id: 5,
    chapter: "Stack",
    subject: "Data structure",
  title:"Question",
    info: `An operating system (OS) is the program that, after being initially loaded into the computer by a boot program, manages all of the other application programs in a computer. `,
  },
  {
    id: 6,
    chapter: "storage system",
    subject: "Operating system",

  title:"Question",
    info: `An operating system (OS) is the program that, after being initially loaded into the computer by a boot program, manages all of the other application programs in a computer.` ,
  },
  {
    id: 7,
    chapter: "Inheritances",
    subject: "OOP",
  title:"Question",
  info: `An operating system (OS) is the program that, after being initially loaded into the computer by a boot program, manages all of the other application programs in a computer. `,
},
  {
    id: 8,
    chapter: "Algebra",
    subject: "Maths",
  title:"Question",
  info: `An operating system (OS) is the program that, after being initially loaded into the computer by a boot program, manages all of the other application programs in a computer. `,
},
  {
    id: 9,
    chapter: "Process system",
    subject: "Operating system",
  title:"Question",
  info: `An operating system (OS) is the program that, after being initially loaded into the computer by a boot program, manages all of the other application programs in a computer. `,
},
  {
    id: 11,
    chapter: "country delight",
    subject: "Maths",
  title:"Question",
  info: `An operating system (OS) is the program that, after being initially loaded into the computer by a boot program, manages all of the other application programs in a computer. `,
},
  {
    id: 12,
    chapter: "Classes",
    subject: "OOP",
  title:"Question",
  info: `An operating system (OS) is the program that, after being initially loaded into the computer by a boot program, manages all of the other application programs in a computer. `,
},
  {
    id: 13,
    chapter: "Queses",
    subject: "Data structure",
  title:"Question",
  info: `An operating system (OS) is the program that, after being initially loaded into the computer by a boot program, manages all of the other application programs in a computer. `,
},
  {
    id: 14,
    chapter: "Link list",
    subject: "Data structure",
  title:"Question",
  info: `An operating system (OS) is the program that, after being initially loaded into the computer by a boot program, manages all of the other application programs in a computer. `,
},
  {
    id: 15,
    chapter: "objects",
    subject: "OOP",
  title:"Question",
  info: `An operating system (OS) is the program that, after being initially loaded into the computer by a boot program, manages all of the other application programs in a computer. `,
},
];
export default book;
